In [2]:
import numpy as np
import pandas as pd

In [3]:
arr = np.arange(1, 11)   # numbers 1 through 10
print(arr)

arr_2x5 = arr.reshape(2, 5)   # 2 rows, 5 columns
print(arr_2x5)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
arr2 = np.arange(1, 21)   # numbers 1 to 20
print(arr2)

subset = arr2[5:15]
print(subset)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11 12 13 14 15]


In [5]:
mean_val = np.mean(arr2)
median_val = np.median(arr2)
std_val = np.std(arr2)

print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)

Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


In [6]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])  

y = np.array([1, 1, 1, 1])        

result = x - y
print(result)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma',
             'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'],
    'age': [25, 32, 28, 45, 22, 38, 29, 41, 26, 33],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'M', 'F', 'M']
}

df = pd.DataFrame(data)
print(df)

      name  age gender
0    Alice   25      F
1      Bob   32      M
2  Charlie   28      M
3    David   45      M
4     Emma   22      F
5    Frank   38      M
6    Grace   29      F
7    Henry   41      M
8      Ivy   26      F
9     Jack   33      M


In [8]:
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager',
                     'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
print(df)

      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   28      M     Analyst
3    David   45      M  Programmer
4     Emma   22      F     Manager
5    Frank   38      M     Analyst
6    Grace   29      F  Programmer
7    Henry   41      M     Manager
8      Ivy   26      F     Analyst
9     Jack   33      M  Programmer


In [9]:
older = df[df['age'] >= 30]
print(older)

    name  age gender  occupation
1    Bob   32      M     Manager
3  David   45      M  Programmer
5  Frank   38      M     Analyst
7  Henry   41      M     Manager
9   Jack   33      M  Programmer


In [10]:
df.to_csv('people.csv', index=False)

df_from_csv = pd.read_csv('people.csv')
print(df_from_csv)

      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   28      M     Analyst
3    David   45      M  Programmer
4     Emma   22      F     Manager
5    Frank   38      M     Analyst
6    Grace   29      F  Programmer
7    Henry   41      M     Manager
8      Ivy   26      F     Analyst
9     Jack   33      M  Programmer
